title: Crypto Market Analysis Blog
description: Daily cryptocurrency market insights and analysis
baseurl: ""
url: "https://cryptowhizard.github.io"
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
