title: Crypto Market Analysis Blog
description: Daily cryptocurrency market insights and analysis
lang: en
timezone: America/New_York
url: "https://cryptowhizard.github.io"
baseurl: "" # set to "" if deployed at root (username.github.io)

theme: minima
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults for SEO and UX
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "Crypto Insights"
      image: "/assets/og/default-og.png" # social share fallback
      sitemap: true
  - scope:
      path: ""
    values:
      layout: default
      sitemap: true

# Plugins (GitHub Pages-supported)
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Feed
feed:
  path: feed.xml

# Kramdown
kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Build settings
future: false
published: true
show_drafts: false

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
