title: Crypto Market Analysis Blog
description: Daily cryptocurrency market insights and analysis
baseurl: ""
url: "https://github.com/cryptowhizard/cryptowhizard.github.io"
markdown: kramdown
highlighter: rouge
theme: minima

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Build settings
future: false
published: true
show_drafts: false

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
